server:
  port: 8080
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
      
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always